# Generated by Django 4.0.4 on 2022-05-27 06:09

import datetime
import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_game',
            field=models.CharField(choices=[('mc', 'Minecraft'), ('fortnite', 'Fortnite'), ('valorant', 'Valorant'), ('lol', 'League of Legends'), ('cod', 'Call of Duty'), ('gta', 'Grand Theft Auto'), ('apex', 'Apex Legends'), ('csgo', 'Counter Strike: Global Offensive'), ('dbd', 'Dead by Daylight'), ('wow', 'World of Warcraft'), ('eft', 'Escape from Tarkov'), ('genshin', 'Genshin Impact'), ('rss', 'Rainbow Six Seige'), ('overwatch', 'Overwatch'), ('pubg', 'PUBG'), ('dota', 'Dota'), ('amogus', 'Among Us'), ('phasma', 'Phasmophobia'), ('fifa', 'Fifa'), ('destiny', 'Destiny'), ('eldenring', 'Elden Ring'), ('roblox', 'Roblox'), ('candycrush', 'Candy Crush'), ('rust', 'rust'), ('wot', 'World of Tanks'), ('vrchat', 'VR Chat'), ('halo', 'Halo'), ('rdr', 'Red Dead Redemption'), ('sot', 'Sea Of Thieves'), ('nba', 'NBA')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sec_fav_game',
            field=models.CharField(choices=[('mc', 'Minecraft'), ('fortnite', 'Fortnite'), ('valorant', 'Valorant'), ('lol', 'League of Legends'), ('cod', 'Call of Duty'), ('gta', 'Grand Theft Auto'), ('apex', 'Apex Legends'), ('csgo', 'Counter Strike: Global Offensive'), ('dbd', 'Dead by Daylight'), ('wow', 'World of Warcraft'), ('eft', 'Escape from Tarkov'), ('genshin', 'Genshin Impact'), ('rss', 'Rainbow Six Seige'), ('overwatch', 'Overwatch'), ('pubg', 'PUBG'), ('dota', 'Dota'), ('amogus', 'Among Us'), ('phasma', 'Phasmophobia'), ('fifa', 'Fifa'), ('destiny', 'Destiny'), ('eldenring', 'Elden Ring'), ('roblox', 'Roblox'), ('candycrush', 'Candy Crush'), ('rust', 'rust'), ('wot', 'World of Tanks'), ('vrchat', 'VR Chat'), ('halo', 'Halo'), ('rdr', 'Red Dead Redemption'), ('sot', 'Sea Of Thieves'), ('nba', 'NBA')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_fav_game',
            field=models.CharField(choices=[('mc', 'Minecraft'), ('fortnite', 'Fortnite'), ('valorant', 'Valorant'), ('lol', 'League of Legends'), ('cod', 'Call of Duty'), ('gta', 'Grand Theft Auto'), ('apex', 'Apex Legends'), ('csgo', 'Counter Strike: Global Offensive'), ('dbd', 'Dead by Daylight'), ('wow', 'World of Warcraft'), ('eft', 'Escape from Tarkov'), ('genshin', 'Genshin Impact'), ('rss', 'Rainbow Six Seige'), ('overwatch', 'Overwatch'), ('pubg', 'PUBG'), ('dota', 'Dota'), ('amogus', 'Among Us'), ('phasma', 'Phasmophobia'), ('fifa', 'Fifa'), ('destiny', 'Destiny'), ('eldenring', 'Elden Ring'), ('roblox', 'Roblox'), ('candycrush', 'Candy Crush'), ('rust', 'rust'), ('wot', 'World of Tanks'), ('vrchat', 'VR Chat'), ('halo', 'Halo'), ('rdr', 'Red Dead Redemption'), ('sot', 'Sea Of Thieves'), ('nba', 'NBA')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
