# Generated by Django 4.0.4 on 2022-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_first_name_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='version',
        ),
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
