# Generated by Django 4.0.5 on 2022-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_version_profile_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_requests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.FileField(default='default-profile-picture.jpg', upload_to='profile_images'),
        ),
    ]
