# Generated by Django 4.0.5 on 2022-06-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chat_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.IntegerField(default=-1)),
                ('users', models.TextField(blank=True)),
                ('messages', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
