# Generated by Django 4.0.5 on 2022-06-27 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_messages_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin', models.IntegerField(default=-1)),
                ('users', models.TextField(blank=True)),
                ('messages', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
