# Generated by Django 4.0.5 on 2022-06-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_chat_delete_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accepting_messages',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessionid',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
