# Generated by Django 4.0.5 on 2022-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profile_date_requests_alter_profile_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accepting_messages',
            field=models.TextField(default=''),
        ),
    ]
