# Generated by Django 4.0.5 on 2022-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_profile_accepting_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_game',
            field=models.TextField(default='Minecraft'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sec_fav_game',
            field=models.TextField(default='Fortnite'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='third_fav_game',
            field=models.TextField(default='Call of Duty'),
        ),
    ]
