# Generated by Django 4.0.5 on 2022-07-17 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profile_fav_game_alter_profile_sec_fav_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dates_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_setup',
            field=models.BooleanField(default=False),
        ),
    ]
